version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile-local
      context: .
    container_name: deploy.app.br
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/
    environment:
      - ENV=local-docker
