version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: deploy.app.br
    ports:
      - "3000:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs/
    environment:
      - ENV=local-docker
