---
name: 'Release and Deploy'

on:
  push:
    branches: [ "main", "master"]
    paths-ignore:
      - '**/README.md'
      - '.github/**'
      - 'docs/**'
jobs:

  release:
    name: Release
    uses: hiperesp/actions/.github/workflows/release.yml@main
    secrets:
      DOKKU_SSH_URL: 'ssh://dokku@deploy.app.br:22/deploy-app'
      DOKKU_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
